### ISSUE TITLE
Intelligently allow user to set Streams configurations with smart guardrails.

### ISSUE THREAD

**Issue by diablouma** [littlehorse-enterprises/littlehorse#478] opened 2023-12-19 15:37 UTC

**Comment by coltmcnealy-lh** [comment] 2024-01-27 07:53
This ticket is quite complicated and necessary for `1.0.0`.

## Allowed Configurations
I see the following things to allow to be configured:

### Producers
We have producers in the GRPC server. We should allow users to configure the following:

- request.timeout.ms
- delivery.timeout.ms
- linger.ms
- batch.size
- buffer.memory

Also note that each Server also has two Kafka Streams topologies, each of which gets its own producer. Should we pass through the configurations to those producers as well? I think so.

### Kafka Streams

We have two kafka streams topologies. We should have some configs which are global, and other configs which can be different per topology.

#### Global Configs
- Session Timeout
- Standby Replicas
- Warmup Replicas
- Replication Factor
- Cluster Partitions
- Rack ID

#### Per-Topology Configs
- Commit Interval
- Stream Threads

### RocksDB

Again, there are some global and some per-topology configs.

#### Global Configs
- Block Cache Size
- Write Buffer Manager Size

The Block Cache is a cache used for reading. The Write Buffer Manager can cap the total size of all write buffers (also known as memtables). RocksDB allows you to configure a single WBM and single Block Cache for _all instances on the same process_, which means we can configure these once across both the topologies.

This is good because it allows users to more easily predict the memory usage of the application irrespective of how many `Task`s are on the host.

#### Per-Topology Configs
- RocksDB Write Buffer Size
- [Maybe] Compaction Style (I think Level compaction all-the-way is what we want here?)

## Setting Defaults
Setting defaults for things like commit interval etc isn't too difficult. But what is difficult is the configurations which should change as the hardware changes. I think we should probably aim for a default configuration (i.e. running the server with no configs set) that has the following characteristics:

- Minimal number of threads (I think 8 is the minimum given how Streams + GRPC work)
- Max of 1.5G memory usage

The problem is that users might run LH on a larger machine and wonder why it's not scaling very well. They would have to configure everything properly.

**Comment by coltmcnealy-lh** [comment] 2024-01-27 07:54
cc @eduwercamacaro @sauljabin  I am open to comments on this before I implement it. I think the PR will be interesting.

I would also like help profiling afterwards to ensure that we can actually get the `1.5G` limit. This might also help with #626, which was memory-bound if I remember correctly.

**Closed** 2024-01-31 04:26 UTC
