### ISSUE TITLE
Add `description` to `MetadataGetable`s

### ISSUE THREAD

**Issue by HazimAr** [littlehorse-enterprises/littlehorse#1051] opened 2024-10-04 20:16 UTC
### Context

Allowing users to attach descriptions to different definitions `TaskDef` `ExternalEventDef` maybe `WfSpec` etc. would allow others with less context to better understand what the workflow is doing.

### Acceptance Criteria

- Custom descriptions for definitions
- Ability to see these definitions on the dashboard

### Components

Dashboard, Server, Python SDK, Go SDK, Java SDK, C# SDK

**Comment by coltmcnealy-lh** [comment] 2024-11-01 14:42
Duplicate of #583

**Closed by coltmcnealy-lh** 2024-11-01 14:42 UTC
Labels: enhancement, server
