### ISSUE TITLE
Support Enum Data Type in the Server

### ISSUE THREAD

**Issue by coltmcnealy-lh** [littlehorse-enterprises/littlehorse#1107] opened 2024-11-06 17:03 UTC
This would be especially useful for:
* User Tasks
* `Variable`s inside a `WfRun`, such as a `order-status` enum.

It would need to be a complex type. Perhaps it could be integrated into #880 .

**Comment by HazimAr** [comment] 2024-11-06 17:38
duplicate of #1101

**Closed by HazimAr** 2024-11-06 17:38 UTC
Labels: feature, server, controversial, clients
