### ISSUE TITLE
Allow UserTask to throw Exception on Timeout

### ISSUE THREAD

**Issue by diablouma** [littlehorse-enterprises/littlehorse#527] opened 2023-12-19 16:19 UTC
Current experience: I’m not sure if it’s possible to put a timeout on a User Task Run.

Desired experience: Can do something like:

{noformat}UserTaskOutput uto = thread.assignTaskToUser(...);

thread.cancelUserTaskAfter(uto, 60 * 60, "too-lazy-to-finish-task");{noformat}

**Comment by coltmcnealy-lh** [comment] 2024-01-17 16:18
Closing as duplicate of #599

**Closed by coltmcnealy-lh** 2024-01-17 16:18 UTC
